# render.yaml
blueprintName: nexora-ai

services:
  - type: web
    name: nexora-ai
    env: docker
    branch: main
    repo: https://github.com/Adyaprana/Nexora.ai
    dockerfilePath: ./Dockerfile

    envVars:
      - key: MISTRAL_API_KEY
        sync: false

